### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by zimny** [Adobe-Marketing-Cloud-Apps/aem-mobile-hybrid-reference#6]
While installing FP3 (as defined in readme), following dependencies are missing:

day/cq61/product:cq-cloudservices-content:1.1.534
day/cq61/product:cq-mcm-content:1.1.188
day/cq60/product:cq-platform-content:1.1.854

please provide a link to proper package.

In addition, it would be nice to add a link to FP3 directly in the readme:
https://www.adobeaemcloud.com/content/marketplace/marketplaceProxy.html?packagePath=/content/companies/public/adobe/packages/cq610/featurepack3/cq-6.1.0-apps-featurepack

**Comment by blefebvre** [comment]
Hi @zimny,

I've added a link to the README for downloading both Apps FP3 and AEM SP1 (a dependency of the featurepack).
